---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.34'
configure_requires:
  ExtUtils::MakeMaker: '6.3'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Exporter-Lite
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/neilbowers/Exporter-Lite.git
version: '0.06'
