---
abstract: 'Moo types for numbers'
author:
  - 'mateu - Mateu X. Hunter (cpan:MATEU) <hunter@missoula.org>'
build_requires:
  Test::Fatal: 0.003
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Types-MooseLike-Numeric
no_index:
  directory:
    - t
    - inc
requires:
  MooX::Types::MooseLike: 0.23
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooX-Types-MooseLike-Numeric
  repository: git://github.com/mateu/MooX-Types-MooseLike-Numeric.git
  x_IRC: irc://irc.perl.org/#web-simple
version: 1.02
