---
abstract: 'dump symbol names or the symbol table'
author:
  - 'Andreas Koenig <andreas.koenig.gmwojprw@franz.ak.mind.de>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
keywords:
  - 'symbol table inspection'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Symdump
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Zlib: '0'
  Test::More: '0'
  perl: '5.004'
resources:
  repository: git://github.com/andk/devel-symdump.git
version: '2.12'
