---
abstract: 'Perl extension for 32 bit Jenkins Hashing Algorithm'
author:
  - 'Dr James Freeman'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-JHash
no_index:
  directory:
    - t
    - inc
requires:
  DynaLoader: 0
  Exporter: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.08
